version: 2.1
orbs:
  1password: onepassword/secrets@1.0.0
jobs:
  test-node:
    machine:
        image: ubuntu-2204:current
    steps:
      - 1password/install-cli:
          version: 2.x.x
      - checkout
      - run:
          shell: op run -- /bin/bash
          environment:
            PIPELINE_EXECUTION_ROLE: op://andmoredev-sandbox/cicd/circleci-pipeline-execution-role-arn
      - aws-cli/setup:
        role-arn: arn:aws:iam::123456789012:role/OIDC-ROLE
        aws-region: us-east-1
        role-session-name: example-session

workflows:
  deploy:
    jobs:
      - test-node