version: 2.1
orbs:
  node: circleci/node@5
  1password: onepassword/secrets@1.0.0
jobs:
  test-node:
    machine:
      image: ubuntu-2204:current
    steps:
      - 1password/install-cli:
          version: 2.x.x
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
workflows:
  build-and-test:
    jobs:
      - test-node