version: 2.1
orbs:
  1password: onepassword/secrets@1.0.0
  aws-cli: circleci/aws-cli@5.1.0
jobs:
  deploy:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - 1password/install-cli:
          version: 2.18.0
      - checkout
      - run:
          shell: op run -- /bin/bash
          environment:
            PIPELINE_EXECUTION_ROLE: op://andmoredev-sandbox/cicd/circleci-pipeline-execution-role-arn
          command: echo 'export MY_ENV_VAR="$PIPELINE_EXECUTION_ROLE"' >> "$BASH_ENV"
      - aws-cli/setup:
          profile_name: default
          role_arn: $MY_ENV_VAR
workflows:
  deploy:
    jobs:
      - deploy