version: 2.1
orbs:
  1password: onepassword/secrets@1.0.0
jobs:
  deploy:
    machine:
        image: ubuntu-2204:current
    steps:
      - 1password/install-cli:
          version: 2.18.0
      - checkout
      - run:
          shell: op run -- /bin/bash
          environment:
            PIPELINE_EXECUTION_ROLE: op://andmoredev-sandbox/cicd/circleci-pipeline-execution-role-arn
          command: |
            echo "This value will be masked: $PIPELINE_EXECUTION_ROLE"
workflows:
  deploy:
    jobs:
      - deploy